# Generated by Django 2.1.4 on 2019-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='alphanumeric identifier', max_length=225)),
                ('contact_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(blank=True, help_text='string', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
